version: "3.9"
services:
  web:
    container_name: cake-sandbox-web
    build:
      context: ./.docker
      dockerfile: Dockerfile-dev
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/cake_app
  db:
    container_name: cake-sandbox-db
    image: "mysql:8"
    ports:
      - "13306:3306"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my_app
      MYSQL_USER: my_app
      MYSQL_PASSWORD: secret
    volumes:
      - ./.docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./.docker/db/data:/var/lib/mysql
      - ./.docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
