version: "3.9"
services:
  web:
    container_name: cake-sandbox-web
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/cake_app
  db:
    container_name: cake-sandbox-db
    image: "mysql:8"
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    volumes:
      - ./.docker/db/etc/mysql/conf.d:/etc/mysql/conf.d
