name: CakePHP App CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    container:
      image: sukun1899/cakephp:4-php8
    env:
      WORKSPACE: /var/www/cake_app
      DATABASE_TEST_URL: ${{ secrets.DATABASE_TEST_URL }}

    services:
      db:
        image: mysql:8
        ports:
          - "3306:3306"
        options: --health-cmd "mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test_my_app
          MYSQL_USER: my_app
          MYSQL_PASSWORD: secret

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - run: |
        rm ${GITHUB_WORKSPACE}/config/.env.example

    - name: Move to workspace
      run: |
        mv ${GITHUB_WORKSPACE}/* ${WORKSPACE}

    - name: composer install
      run: |
        composer install --prefer-dist -d ${WORKSPACE}

    - name: Run PHPUnit
      run: |
        cd ${WORKSPACE}
        vendor/bin/phpunit

#  coding-standard:
#    name: Coding Standard
#    runs-on: ubuntu-18.04
#
#    steps:
#    - uses: actions/checkout@v1
#      with:
#        fetch-depth: 1
#
#    - name: Setup PHP
#      uses: shivammathur/setup-php@v2
#      with:
#        php-version: '7.2'
#        extensions: mbstring, intl
#        coverage: none
#
#    - name: composer install
#      run: composer install
#
#    - name: Run PHP CodeSniffer
#      run: composer cs-check

#  static-analysis:
#    name: Static Analysis
#    runs-on: ubuntu-18.04
#
#    steps:
#    - uses: actions/checkout@v1
#      with:
#        fetch-depth: 1
#
#    - name: Setup PHP
#      uses: shivammathur/setup-php@v2
#      with:
#        php-version: '7.2'
#        extensions: mbstring, intl
#        coverage: none
#
#    - name: composer install
#      run: composer require --dev phpstan/phpstan:^0.12
#
#    - name: Run phpstan
#      run: vendor/bin/phpstan.phar analyse
